## This file was created automatically, do not edit by hand.
#' Precipitation percent due to R95p days
#'
#' Let infile1 be a time series RR of the daily precipitation amount at wet days (precipitation &gt;= 1 mm) and infile2 be the 95th percentile RRn95 of the daily precipitation amount at wet days for any period used as reference. Then the ratio of the precipitation sum at wet days with RR &gt; RRn95 to the total precipitation sum is calculated. RRn95 is calculated as the 95th percentile of all wet days of a given climate reference period. Usually infile2 is generated by the operator ydaypctl,95. The date information of a timestep in outfile is the date of the last contributing timestep in infile1.
#'
#' 
#'
#' 
#'
#' @name ecar95ptot
NULL
