# fmt: skip file
## This file was created automatically, do not edit by hand.
#' Multiyear seasonal arithmetic
#'
#' This module performs simple arithmetic of a time series and one timestep with the same season. For each field in infile1 the corresponding field of the timestep in infile2 with the same season is used. The input files need to have the same structure with the same variables. Usually infile2 is generated by an operator of the module YSEASSTAT. 
#'
#' @details
#'     yseasadd  Add multi-year seasonal time series
#'               Adds a time series and a multi-year seasonal time series.
#'     yseassub  Subtract multi-year seasonal time series
#'               Subtracts a time series and a multi-year seasonal time series.
#'     yseasmul  Multiply multi-year seasonal time series
#'               Multiplies a time series and a multi-year seasonal time series.
#'     yseasdiv  Divide multi-year seasonal time series
#'               Divides a time series and a multi-year seasonal time series.
#'
#' 
#'
#' @returns
#' Operators that output one or more files return a character vector to the
#' output files.
#'
#' Operators that output an indefinite number of files return a string with the
#' basename of the files.
#'
#' Operators that don't return filenames return a character vector with the
#' string output.
#' @name yseasarith
NULL
