## This file was created automatically, do not edit by hand.
#' Monthly arithmetic
#'
#' This module performs simple arithmetic of a time series and one timestep with the same month and year. For each field in infile1 the corresponding field of the timestep in infile2 with the same month and year is used. The input files need to have the same structure with the same variables. Usually infile2 is generated by an operator of the module MONSTAT. 
#'
#' @details
#'     monadd  Add monthly time series
#'             Adds a time series and a monthly time series.
#'     monsub  Subtract monthly time series
#'             Subtracts a time series and a monthly time series.
#'     monmul  Multiply monthly time series
#'             Multiplies a time series and a monthly time series.
#'     mondiv  Divide monthly time series
#'             Divides a time series and a monthly time series.
#'
#' 
#'
#' @returns
#' Operators that output one or more files return a character vector to the
#' output files.
#'
#' Operators that output an indefinite number of files return a string with the
#' basename of the files.
#'
#' Operatos that don't return filenames return a character vector with the
#' string output.
#' @name monarith
NULL
