## This file was created automatically, do not edit by hand.
#' Daily arithmetic
#'
#' This module performs simple arithmetic of a time series and one timestep with the same day, month and year. For each field in infile1 the corresponding field of the timestep in infile2 with the same day, month and year is used. The input files need to have the same structure with the same variables. Usually infile2 is generated by an operator of the module DAYSTAT. 
#'
#' @details
#'     dayadd  Add daily time series
#'             Adds a time series and a daily time series.
#'     daysub  Subtract daily time series
#'             Subtracts a time series and a daily time series.
#'     daymul  Multiply daily time series
#'             Multiplies a time series and a daily time series.
#'     daydiv  Divide daily time series
#'             Divides a time series and a daily time series.
#'
#' 
#'
#' @name dayarith
NULL
