## This file was created automatically, do not edit by hand.
#' Very wet days wrt 95th percentile of reference period
#'
#' Let infile1 be a time series RR of the daily precipitation amount at wet days (precipitation &gt;= 1 mm) and infile2 be the 95th percentile RRn95 of the daily precipitation amount at wet days for any period used as reference. Then the percentage of wet days with RR &gt; RRn95 is calculated. RRn95 is calculated as the 95th percentile of all wet days of a given climate reference period. Usually infile2 is generated by the operator ydaypctl,95. The date information of a timestep in outfile is the date of the last contributing timestep in infile1.
#'
#' 
#'
#' 
#'
#' @returns
#' Operators that output one or more files return a character vector to the
#' output files.
#'
#' Operators that output an indefinite number of files return a string with the
#' basename of the files.
#'
#' Operatos that don't return filenames return a character vector with the
#' string output.
#' @name ecar95p
NULL
