# fmt: skip file
## This file was created automatically, do not edit by hand.
#' Multiyear daily arithmetic
#'
#' This module performs simple arithmetic of a time series and one timestep with the same day of year. For each field in infile1 the corresponding field of the timestep in infile2 with the same day of year is used. The input files need to have the same structure with the same variables. Usually infile2 is generated by an operator of the module YDAYSTAT. 
#'
#' @details
#'     ydayadd  Add multi-year daily time series
#'              Adds a time series and a multi-year daily time series.
#'     ydaysub  Subtract multi-year daily time series
#'              Subtracts a time series and a multi-year daily time series.
#'     ydaymul  Multiply multi-year daily time series
#'              Multiplies a time series and a multi-year daily time series.
#'     ydaydiv  Divide multi-year daily time series
#'              Divides a time series and a multi-year daily time series.
#'
#' 
#'
#' @returns
#' Operators that output one or more files return a character vector to the
#' output files.
#'
#' Operators that output an indefinite number of files return a string with the
#' basename of the files.
#'
#' Operators that don't return filenames return a character vector with the
#' string output.
#' @name ydayarith
NULL
