## This file was created automatically, do not edit by hand.
#' Daily arithmetic
#'
#' This module performs simple arithmetic of a time series and one timestep with the same day, month and year. For each field in infile1 the corresponding field of the timestep in infile2 with the same day, month and year is used. The input files need to have the same structure with the same variables. Usually infile2 is generated by an operator of the module DAYSTAT. 
#'
#' @details
#'     dayadd  Add daily time series
#'             Adds a time series and a daily time series.
#'     daysub  Subtract daily time series
#'             Subtracts a time series and a daily time series.
#'     daymul  Multiply daily time series
#'             Multiplies a time series and a daily time series.
#'     daydiv  Divide daily time series
#'             Divides a time series and a daily time series.
#'
#' 
#'
#' @returns
#' Operators that output one or more files return a character vector to the
#' output files.
#'
#' Operators that output an indefinite number of files return a string with the
#' basename of the files.
#'
#' Operatos that don't return filenames return a character vector with the
#' string output.
#' @name dayarith
NULL
