## This file was created automatically, do not edit by hand.
#' Wet days wrt 90th percentile of reference period
#'
#' Let infile1 be a time series RR of the daily precipitation amount at wet days (precipitation &gt;= 1 mm) and infile2 be the 90th percentile RRn90 of the daily precipitation amount at wet days for any period used as reference. Then the percentage of wet days with RR &gt; RRn90 is calculated. RRn90 is calculated as the 90th percentile of all wet days of a given climate reference period. Usually infile2 is generated by the operator ydaypctl,90. The date information of a timestep in outfile is the date of the last contributing timestep in infile1.
#'
#' 
#'
#' 
#'
#' @name ecar90p
NULL
