## This file was created automatically, do not edit by hand.
#' Multiyear hourly arithmetic
#'
#' This module performs simple arithmetic of a time series and one timestep with the same hour and day of year. For each field in infile1 the corresponding field of the timestep in infile2 with the same hour and day of year is used. The input files need to have the same structure with the same variables. Usually infile2 is generated by an operator of the module YHOURSTAT. 
#'
#' @details
#'     yhouradd  Add multi-year hourly time series
#'               Adds a time series and a multi-year hourly time series.
#'     yhoursub  Subtract multi-year hourly time series
#'               Subtracts a time series and a multi-year hourly time series.
#'     yhourmul  Multiply multi-year hourly time series
#'               Multiplies a time series and a multi-year hourly time series.
#'     yhourdiv  Divide multi-year hourly time series
#'               Divides a time series and a multi-year hourly time series.
#'
#' 
#'
#' @name yhourarith
NULL
