# fmt: skip file
## This file was created automatically, do not edit by hand.
#' Yearly arithmetic
#'
#' This module performs simple arithmetic of a time series and one timestep with the same year. For each field in infile1 the corresponding field of the timestep in infile2 with the same year is used. The header information in infile1 have to be the same as in infile2. Usually infile2 is generated by an operator of the module YEARSTAT. 
#'
#' @details
#'     yearadd  Add yearly time series
#'              Adds a time series and a yearly time series.
#'     yearsub  Subtract yearly time series
#'              Subtracts a time series and a yearly time series.
#'     yearmul  Multiply yearly time series
#'              Multiplies a time series and a yearly time series.
#'     yeardiv  Divide yearly time series
#'              Divides a time series and a yearly time series.
#'
#' 
#'
#' @returns
#' Operators that output one or more files return a character vector to the
#' output files.
#'
#' Operators that output an indefinite number of files return a string with the
#' basename of the files.
#'
#' Operators that don't return filenames return a character vector with the
#' string output.
#' @name yeararith
NULL
